### ISSUE TITLE
短链接无法使用

### ISSUE THREAD

**Issue by MFYDev** [CareyWang/bitly#1]
api token完全正确，后端显示的是200，正常运行，但是返回的数据没有就很奇怪，不管是我的还是您的都这样，请问是哪里出的问题呢？

**Comment by CareyWang** [comment]
如果是前端api调用，可以确认下后端是否正确配置了跨域访问。
如果是直接请求返回为空，可能是url格式不正确，比如长链接base64encode前，未加“https://”，此时bitly会响应为空。

**Comment by MFYDev** [comment]
我首先使用默认的您的shortUrl的网址，longUrl后面是有 https:// 的，
比如用您的 https://api.wcc.best/short?longUrl=https://www.baidu.com
返回的是空的，跨域的有加，也不行

**Comment by CareyWang** [comment]
@FanyangMengDev url需经过base64encode。后续会更新一下readme

**Comment by MFYDev** [comment]
哦哦原来是这样~感谢感谢~

**Comment by MFYDev** [comment]
短链接其实还有一个问题就是无法自动到剪贴板，尽管显示已经到剪贴板了。这个刚刚在您的网站上测试了一下发现也是这样，既没有显示在长连接下，也没有到剪贴板

**Comment by CareyWang** [comment]
@FanyangMengDev Chrome测试没有问题

**Comment by MFYDev** [comment]
我用的firefox和edge都不可以，我去用chrome测试一下

**Comment by MFYDev** [comment]
测试了一下，确实只有Chrome能够使用，感觉这个可以做一个适配，目前firefox和edge都不行，Chrome用久了感觉不太保护隐私不太使用了，希望可以找时间支持一下~

**Comment by MFYDev** [comment]
或者说可以不直接到剪贴板，而是显示在长链接下方也是可以的，感觉这样的话会更方便一些

**Comment by CareyWang** [comment]
@FanyangMengDev 可以的，后续更新

**Comment by MFYDev** [comment]
非常感谢Carey，这个工程真的很大程度上简化了操作，我看subconverter 0.4.2版本加了一些新的东西，也希望前端这里能加入一些，不过目前来看是够用的。已Star并Watch，期待下一次更新~

**Comment by MFYDev** [comment]
我刚刚看了一下bitly的文档，bitly官方回复说链接永远不会被删除，所以我担心使用bitly会存在安全性问题，短链接是否有另外一种安全的解决方法感觉是一个问题，我自己这边目前先删除了前端的短连接生成，换成我自己的YOURLS了，YOURLS毕竟可以自己管理自己的短链接，需要的话还可以设置密码，感觉比较好

**Comment by CareyWang** [comment]
@FanyangMengDev 建议都使用自己服务，几个后端可根据自己需求自行完善。
